### ISSUE TITLE
add -u and -p for user and password

### ISSUE THREAD

**Issue by Sylche** [ntokos/check-aloxe#1]
In my job i need multi user and or password then i do a modification

Line 49 : 

Usage: %s [-h] [-v] [-t] -u <username> -p <password> -H <host> -m <mode>

Line 98 : 

$plugin->add_arg(
           spec => 'username|u=s',
           help => "Username",
           required => 1
);

$plugin->add_arg(
           spec => 'password|p=s',
           help => "Password",
           required => 1
);

Line 608 :  

my $TELNET_USER = $plugin->opts->username;
my $TELNET_PASS = $plugin->opts->password;

**Comment by ntokos** [comment]
Thank you for the suggestion.
Just implemented this and committed changes as a new plugin version.
